{{- if .Values.naiLabs.enabled }}
# NAI Labs HTTP Route for routing traffic through the gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nai-labs-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-labs-httproute
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: nai-ingress-gateway
  rules:
    - matches: # NAI Labs
        - path:
            type: PathPrefix
            value: /nai/apps/rag
      timeouts:
        request: 360s
      backendRefs:
        - name: nai-labs
          namespace: {{ .Release.Namespace }}
          port: 8080
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Strict-Transport-Security
                value: max-age=31536000; includeSubDomains
              - name: X-Frame-Options
                value: SAMEORIGIN
              - name: Content-Security-Policy
                value: >-
                  default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-src 'self';
{{- end }}
