apiVersion: v2
appVersion: 0.1.0
dependencies:
- name: oauth2-proxy
  repository: ""
  version: 7.12.17
- name: nai-clickhouse-keeper
  repository: ""
  version: 1.1.0
- name: nai-clickhouse-server
  repository: ""
  version: 1.0.6
- name: nai-clickhouse-schemas
  repository: ""
  version: 1.1.3
description: A Helm chart for NAI core components
name: nai-core
type: application
version: 2.5.0
