apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nai-v4-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.naiAIGateway.enabled }}
    nai.nutanix.com/extauth: enabled
    {{- end }}
    {{- include "nai-core.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: nai-ingress-gateway
  rules:
    - matches: # NAI API v4.0.a1 Management APIs
        - path:
            type: PathPrefix
            value: /api/enterpriseai/v4.0.a1/
      backendRefs:
        - name: nai-api
          namespace: {{ .Release.Namespace }}
          port: 7000