apiVersion: v1
kind: ServiceAccount
metadata:
  name: nai-model-processor-sa
  namespace: nai-admin
  labels:
    {{- include "nai-core.labels" . | nindent 4 }}
{{- if .Values.imagePullSecret.name }}
imagePullSecrets:
- name: {{ .Values.imagePullSecret.name }}
{{- end }}