apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: nai-envoyproxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          {{- if index .Values "gateway-helm" "global" "imagePullSecrets" }}
          imagePullSecrets:
            {{- range index .Values "gateway-helm" "global" "imagePullSecrets" }}
            - name: {{ .name }}
          {{- end }}
          {{- end }}
        container:
          image: {{ index .Values "global" "repository" }}/{{ index .Values "gateway-helm" "global" "images" "naiProxy" "image" }}