apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: nai-envoyproxy
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          {{- if .Values.gatewayHelm.global.imagePullSecrets }}
          imagePullSecrets:
            {{- range .Values.gatewayHelm.global.imagePullSecrets }}
            - name: {{ .name }}
          {{- end }}
          {{- end }}
        container:
          image: "{{ .Values.global.repository }}/{{ .Values.gatewayHelm.global.images.naiProxy.image }}"