apiVersion: v1
kind: Secret
metadata:
  name: nai-clickhouse-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: nai-clickhouse
    {{- include "nai-core.labels" . | nindent 4 }}
type: Opaque
data:
  CLICKHOUSE_USERNAME: {{ index .Values "nai-clickhouse-server" "clickhouse" "users" "admin" "username" | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ index .Values "nai-clickhouse-server" "clickhouse" "users" "admin" "password" | b64enc | quote }}
  CLICKHOUSE_DATABASE: {{ "nai_metrics" | b64enc | quote }}
  CLICKHOUSE_ADDRESS: {{ printf "chcluster1-ep.%s.svc.cluster.local:9000" .Release.Namespace | b64enc | quote }}
  CLICKHOUSE_COUNTER_TABLE: {{ "ch_metrics_sum_table" | b64enc | quote }}
  CLICKHOUSE_GAUGE_TABLE: {{ "ch_metrics_gauge_table" | b64enc | quote }}
  CLICKHOUSE_HISTOGRAM_TABLE: {{ "ch_metrics_histogram_table" | b64enc | quote }}