apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nai-operators-helm-hooks-clusterrole
  labels:
    app.kubernetes.io/component: nai-helm-hooks
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "nai-operators.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get